### ISSUE TITLE
Your VS Code extension is affected by a security issue

### ISSUE THREAD

**Issue by auchenberg** [openlawlibrary/codify#1]
Hi,

Kenneth here from the VS Code team.

Your extension is affected by https://code.visualstudio.com/blogs/2018/11/26/event-stream, as your extension is using `flatmap-stream v0.1.0`

We will need to take action to block your extension if your extension isn't updated in a reasonable timeframe.

Please get in touch at kennau@microsoft.com

/k

**Comment by augb** [comment]
Thanks. I have unpublished the extension. Will follow-up via email.

**Comment by augb** [comment]
v2018.10.1 was published using the latest `vscode` release.

**Comment by auchenberg** [comment]
Wonderful, thanks for the prompt action!
